package me.kavin.piped.utils;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import me.kavin.piped.utils.obj.*;
import org.schabi.newpipe.extractor.InfoItem;
import org.schabi.newpipe.extractor.channel.ChannelInfoItem;
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandler;
import org.schabi.newpipe.extractor.linkhandler.ReadyChannelTabListLinkHandler;
import org.schabi.newpipe.extractor.playlist.PlaylistInfoItem;
import org.schabi.newpipe.extractor.services.youtube.ItagItem;
import org.schabi.newpipe.extractor.stream.AudioTrackType;
import org.schabi.newpipe.extractor.stream.StreamInfo;
import org.schabi.newpipe.extractor.stream.StreamInfoItem;
import org.schabi.newpipe.extractor.stream.StreamType;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

import static me.kavin.piped.utils.URLUtils.*;

public class CollectionUtils {

    public static Streams collectStreamInfo(ExtractedVideo extracted) {
        final StreamInfo info = extracted.info;

        final List<Subtitle> subtitles = new ObjectArrayList<>();
        final List<ChapterSegment> chapters = new ObjectArrayList<>();

        info.getStreamSegments().forEach(segment -> chapters.add(new ChapterSegment(segment.getTitle(), rewriteURL(segment.getPreviewUrl()),
                segment.getStartTimeSeconds())));

        final List<PreviewFrames> previewFrames = new ObjectArrayList<>();

        info.getPreviewFrames().forEach(frame -> previewFrames.add(new PreviewFrames(frame.getUrls().stream().map(URLUtils::rewriteURL).toList(), frame.getFrameWidth(),
                frame.getFrameHeight(), frame.getTotalCount(), frame.getDurationPerFrame(), frame.getFramesPerPageX(),
                frame.getFramesPerPageY())));

        info.getSubtitles()
                .forEach(subtitle -> subtitles.add(new Subtitle(rewriteURL(subtitle.getContent()),
                        subtitle.getFormat().getMimeType(), subtitle.getDisplayLanguageName(),
                        subtitle.getLanguageTag(), subtitle.isAutoGenerated())));

        final List<PipedStream> videoStreams = new ObjectArrayList<>();
        final List<PipedStream> audioStreams = new ObjectArrayList<>();

        boolean livestream = info.getStreamType() == StreamType.LIVE_STREAM;

        final Map<String, String> extraParams = Map.of(
//                "ump", "1",
//                "srfvp", "1"
        );

        if (!livestream) {
            info.getVideoOnlyStreams().forEach(stream -> videoStreams.add(new PipedStream(stream.getItag(), rewriteVideoURL(stream.getContent(), extraParams),
                    String.valueOf(stream.getFormat()), stream.getResolution(), stream.getFormat().getMimeType(), true,
                    stream.getBitrate(), stream.getInitStart(), stream.getInitEnd(), stream.getIndexStart(),
                    stream.getIndexEnd(), stream.getCodec(), stream.getWidth(), stream.getHeight(), stream.getFps(), stream.getItagItem().getContentLength())));
            info.getVideoStreams()
                    .forEach(stream -> videoStreams
                            .add(new PipedStream(stream.getItag(), rewriteVideoURL(stream.getContent(), Map.of()), String.valueOf(stream.getFormat()),
                                    stream.getResolution(), stream.getFormat().getMimeType(), false, stream.getItagItem().getContentLength())));

            info.getAudioStreams()
                    .forEach(stream -> audioStreams.add(new PipedStream(stream.getItag(), rewriteVideoURL(stream.getContent(), extraParams),
                            String.valueOf(stream.getFormat()), stream.getAverageBitrate() + " kbps",
                            stream.getFormat().getMimeType(), false, stream.getBitrate(), stream.getInitStart(),
                            stream.getInitEnd(), stream.getIndexStart(), stream.getIndexEnd(), stream.getItagItem().getContentLength(), stream.getCodec(), stream.getAudioTrackId(),
                            stream.getAudioTrackName(), Optional.ofNullable(stream.getAudioTrackType()).map(Enum::name).orElse(null),
                            Optional.ofNullable(stream.getAudioLocale()).map(Locale::toLanguageTag).orElse(null)
                    )));
        }

        final List<ContentItem> relatedStreams = collectRelatedItems(info.getRelatedItems());

        final List<MetaInfo> metaInfo = new ObjectArrayList<>();
        info.getMetaInfo().forEach(metaInfoItem -> metaInfo.add(new MetaInfo(metaInfoItem.getTitle(), metaInfoItem.getContent().getContent(),
                metaInfoItem.getUrls(), metaInfoItem.getUrlTexts()
        )));

        // Build the legacy mode block (may be null only if nothing was extracted at all).
        final String legacyDash = rewriteVideoURL(info.getDashMpdUrl(), Map.of());
        final String legacyHls = rewriteVideoURL(info.getHlsUrl(), Map.of());
        final boolean legacyAvailable = legacyDash != null || legacyHls != null
                || !audioStreams.isEmpty() || !videoStreams.isEmpty();
        final LegacyMode legacy = legacyAvailable
                ? new LegacyMode(legacyDash, legacyHls, audioStreams, videoStreams)
                : null;

        // Build the SABR mode block when the extractor surfaced a SABR endpoint at the boundary.
        // Livestreams are force-legacy per architecture decision #17.
        final SabrSession sabr = (!livestream && extracted.sabrUrl != null && extracted.sabrUstreamerConfig != null)
                ? buildSabrSession(extracted.sabrUrl, extracted.sabrUstreamerConfig,
                                   extracted.sabrCpn, extracted.sabrFormats)
                : null;

        final AvailableModes availableModes = new AvailableModes(legacy, sabr);
        final String defaultMode = sabr != null ? "sabr" : "legacy";

        return new Streams(info.getName(), info.getDescription().getContent(),
                info.getTextualUploadDate(), info.getUploadDate() != null ? info.getUploadDate().offsetDateTime().toInstant().toEpochMilli() : -1,
                info.getUploaderName(), substringYouTube(info.getUploaderUrl()), getLastThumbnail(info.getUploaderAvatars()),
                getLastThumbnail(info.getThumbnails()), info.getDuration(), info.getViewCount(), info.getLikeCount(), info.getDislikeCount(),
                info.getUploaderSubscriberCount(), info.isUploaderVerified(),
                relatedStreams, subtitles, livestream, null, info.getCategory(), info.getLicence(),
                info.getPrivacy().name().toLowerCase(), info.getTags(), metaInfo, chapters, previewFrames,
                availableModes, defaultMode);
    }

    /**
     * Inject an LBRY-sourced {@link PipedStream} at the front of the legacy
     * mode's videoStreams list. Creates the legacy block on demand if a video
     * happens to have no legacy data at all (rare; usually SABR-only videos
     * still expose at least the legacy progressive itag 18).
     */
    public static void prependLegacyVideoStream(Streams streams, PipedStream entry) {
        if (streams.availableModes == null) {
            streams.availableModes = new AvailableModes(null, null);
        }
        if (streams.availableModes.legacy == null) {
            streams.availableModes.legacy = new LegacyMode(null, null,
                    new ObjectArrayList<>(), new ObjectArrayList<>());
        }
        streams.availableModes.legacy.videoStreams.add(0, entry);
    }

    /**
     * Build the SABR session block from the SABR endpoint + ustreamer config and
     * the per-format metadata list (sourced from NPE's SABR-aware extractor
     * getters, see {@code YoutubeStreamExtractor.getAndroidSabrAvailableFormats()}).
     *
     * <p>The shape of {@link SabrFormat} mirrors FreeTube's SabrManifest format
     * (https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/helpers/player/SabrManifestParser.js)
     * so the frontend can hand it straight to the vendored {@code SabrManifestParser}.</p>
     */
    private static SabrSession buildSabrSession(String sabrUrl,
                                                String ustreamerConfig,
                                                String cpn,
                                                List<ItagItem> sabrItagItems) {
        final String proxiedSessionUrl = signSabrUrl(sabrUrl, cpn);

        final List<SabrFormat> formats = new ArrayList<>(sabrItagItems.size());
        for (ItagItem itag : sabrItagItems) {
            if (itag.isDrc()) continue;
            formats.add(toSabrFormat(itag));
        }
        return new SabrSession(proxiedSessionUrl, ustreamerConfig, cpn, formats);
    }

    private static SabrFormat toSabrFormat(ItagItem itagItem) {
        final SabrFormat f = new SabrFormat();
        f.itag = itagItem.id;
        f.lastModified = itagItem.getLastModified() > 0
                ? String.valueOf(itagItem.getLastModified())
                : null;
        f.xtags = itagItem.getXtags();
        f.bitrate = itagItem.getBitrate();

        // Reconstruct the full mimeType with codecs="..." so SabrManifestParser
        // can extract both fields directly.
        String mimeType = itagItem.getMediaFormat() != null
                ? itagItem.getMediaFormat().getMimeType()
                : null;
        final String codec = itagItem.getCodec();
        if (mimeType != null && codec != null && !codec.isEmpty()) {
            mimeType = mimeType + "; codecs=\"" + codec + "\"";
        }
        f.mimeType = mimeType;
        f.approxDurationMs = itagItem.getApproxDurationMs() > 0 ? itagItem.getApproxDurationMs() : null;

        if (itagItem.getInitStart() >= 0 && itagItem.getInitEnd() > 0) {
            f.initRange = new SabrFormat.Range(itagItem.getInitStart(), itagItem.getInitEnd());
        }
        if (itagItem.getIndexStart() >= 0 && itagItem.getIndexEnd() > 0) {
            f.indexRange = new SabrFormat.Range(itagItem.getIndexStart(), itagItem.getIndexEnd());
        }

        f.width = itagItem.getWidth() > 0 ? itagItem.getWidth() : null;
        f.height = itagItem.getHeight() > 0 ? itagItem.getHeight() : null;
        f.frameRate = itagItem.getFps() > 0 ? itagItem.getFps() : null;
        f.quality = itagItem.getQuality();

        if (itagItem.getAudioLocale() != null) {
            f.language = itagItem.getAudioLocale().toLanguageTag();
        }
        f.audioSampleRate = itagItem.getSampleRate() > 0 ? itagItem.getSampleRate() : null;
        f.audioChannels = itagItem.getAudioChannels() > 0 ? itagItem.getAudioChannels() : null;
        f.audioTrackId = itagItem.getAudioTrackId();
        f.label = itagItem.getAudioTrackName();

        f.isDrc = itagItem.isDrc() ? Boolean.TRUE : null;
        final AudioTrackType trackType = itagItem.getAudioTrackType();
        if (trackType != null) {
            switch (trackType) {
                case ORIGINAL:
                    f.isOriginal = Boolean.TRUE;
                    break;
                case DUBBED:
                    f.isDubbed = Boolean.TRUE;
                    break;
                case DESCRIPTIVE:
                    f.isDescriptive = Boolean.TRUE;
                    break;
                case SECONDARY:
                    f.isSecondary = Boolean.TRUE;
                    break;
            }
        } else if (itagItem.itagType == ItagItem.ItagType.AUDIO && !itagItem.isDrc()) {
            // Single-track audio (no audioTrackType means YouTube didn't expose
            // multi-language info). Default to "original" so the frontend's
            // SabrManifestParser tags it with role 'main' — its bandwidth-pick
            // fallback in SabrSchemePlugin requires at least one variant with
            // the 'main' role to exist.
            f.isOriginal = Boolean.TRUE;
        }

        return f;
    }

    public static List<ContentItem> collectRelatedItems(List<? extends InfoItem> items) {
        return items
                .stream()
                .parallel()
                .map(item -> {
                    if (item instanceof StreamInfoItem) {
                        return collectRelatedStream(item);
                    } else if (item instanceof PlaylistInfoItem) {
                        return collectRelatedPlaylist(item);
                    } else if (item instanceof ChannelInfoItem) {
                        return collectRelatedChannel(item);
                    } else {
                        throw new RuntimeException(
                                "Unknown item type: " + item.getClass().getName());
                    }
                }).toList();
    }

    private static StreamItem collectRelatedStream(Object o) {

        StreamInfoItem item = (StreamInfoItem) o;

        return new StreamItem(substringYouTube(item.getUrl()), item.getName(),
                getLastThumbnail(item.getThumbnails()),
                item.getUploaderName(), substringYouTube(item.getUploaderUrl()),
                getLastThumbnail(item.getUploaderAvatars()), item.getTextualUploadDate(),
                item.getShortDescription(), item.getDuration(),
                item.getViewCount(), item.getUploadDate() != null ?
                item.getUploadDate().offsetDateTime().toInstant().toEpochMilli() : -1,
                item.isUploaderVerified(), item.isShortFormContent());
    }

    private static PlaylistItem collectRelatedPlaylist(Object o) {

        PlaylistInfoItem item = (PlaylistInfoItem) o;

        return new PlaylistItem(substringYouTube(item.getUrl()), item.getName(),
                getLastThumbnail(item.getThumbnails()),
                item.getUploaderName(), substringYouTube(item.getUploaderUrl()),
                item.isUploaderVerified(),
                item.getPlaylistType().name(), item.getStreamCount());
    }

    private static ChannelItem collectRelatedChannel(Object o) {

        ChannelInfoItem item = (ChannelInfoItem) o;

        return new ChannelItem(substringYouTube(item.getUrl()), item.getName(),
                getLastThumbnail(item.getThumbnails()),
                item.getDescription(), item.getSubscriberCount(), item.getStreamCount(),
                item.isVerified());
    }

    public static List<ReadyChannelTabListLinkHandler> collectPreloadedTabs(List<ListLinkHandler> tabs) {
        return tabs
                .stream()
                .filter(ReadyChannelTabListLinkHandler.class::isInstance)
                .map(ReadyChannelTabListLinkHandler.class::cast)
                .toList();
    }
}
